language: python
dist: trusty
sudo: false

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
   - ./setup.py develop
   - pip3 install pytest-httpbin
   - pip3 install git+https://github.com/python-trio/trio.git
   - pip3 install git+https://github.com/dabeaz/curio.git
   - pip3 install pylint
   - pip3 install multio

script:
  - pytest tests/test_curio.py --verbose --tb=native
  - pytest tests/test_trio.py --verbose --tb=native
  - pytest tests/test_request_object.py --verbose --tb=native
  - pytest tests/test_response_objects.py --verbose --tb=native
  # - pylint asks tests
  # temp disable until bugfix for
  # AttributeError: 'FunctionDef' object has no attribute 'ancestors'

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
